name: Label new PRs
description: Automatically label new pull requests with "needs review"
author: Abhay Chauhan

inputs:
  label:
    description: 'The label to add to new pull requests'
    required: true
  gh-token:
    description: 'GitHub token with permissions to add labels'
    required: true

runs:
  using: "node20"
  main: "dist/main.js"

branding:
  icon: "code"
  color: "blue"