name: Label new PRs
description: Automatically label new pull requests with "needs review"
author: Abhay Chauhan

inputs:
  name:
    description: 'Name of the person to greet'
    required: true
    default: 'World'

runs:
  using: "node20"
  main: "dist/index.js"