name: git-cli

on:
  push:

jobs:
  cli:
    runs-on: ubuntu-latest
    with:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - run: env
      - run: gh auth status
