name: hello-world

permissions:
  pull-requests: write


on:
  pull_request:
    

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Printing with Python
        run: print("Hello, World!")
        shell: python
