name: PR Commit Commenter

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  check-commit-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Commit Message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          echo "msg=$COMMIT_MSG" >> $GITHUB_OUTPUT

      
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'